// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZrTs-MtLV5RfHrlijICSDZsFLcD8zF4',
    appId: '1:228240860351:web:b790a22a85366fe210d20a',
    messagingSenderId: '228240860351',
    projectId: 'lopsi-5eaec',
    authDomain: 'lopsi-5eaec.firebaseapp.com',
    storageBucket: 'lopsi-5eaec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvgrDPd1inqtebfHFgql1xG-lF-pNGN8',
    appId: '1:228240860351:android:0726b7f0d60fe4a810d20a',
    messagingSenderId: '228240860351',
    projectId: 'lopsi-5eaec',
    storageBucket: 'lopsi-5eaec.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZrTs-MtLV5RfHrlijICSDZsFLcD8zF4',
    appId: '1:228240860351:web:57a5a468ec99e9c010d20a',
    messagingSenderId: '228240860351',
    projectId: 'lopsi-5eaec',
    authDomain: 'lopsi-5eaec.firebaseapp.com',
    storageBucket: 'lopsi-5eaec.firebasestorage.app',
  );
}
